# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from foundationallm.cli.core.aaz import *


@register_command_group(
    "vectorization vectorizationrequest",
)
class __CMDGroup(AAZCommandGroup):
    """vectorizationrequest
    """
    pass


__all__ = ["__CMDGroup"]
