# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from foundationallm.cli.core.aaz import *


@register_command(
    "vectorization vectorizationrequest show",
)
class Show(AAZCommand):
    """show
    """

    _aaz_info = {
        "version": "2024-02-16",
        "resources": [
            ["fllm-plane", "/instances/{}/providers/foundationallm.vectorization/vectorizationrequests/{}", "2024-02-16"],
        ]
    }

    def _handler(self, command_args):
        super()._handler(command_args)
        self._execute_operations()
        return self._output()

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.instance_id = AAZStrArg(
            options=["--instance-id"],
            required=True,
        )
        _args_schema.name = AAZStrArg(
            options=["--name"],
            required=True,
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        self.VectorizationrequestsGet(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class VectorizationrequestsGet(AAZHttpOperation):
        CLIENT_TYPE = "FllmClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/instances/{instanceId}/providers/FoundationaLLM.Vectorization/vectorizationrequests/{name}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "instanceId", self.ctx.args.instance_id,
                    required=True,
                ),
                **self.serialize_url_param(
                    "name", self.ctx.args.name,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2024-02-16",
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZListType()

            _schema_on_200 = cls._schema_on_200
            _schema_on_200.Element = AAZObjectType()

            _element = cls._schema_on_200.Element
            _element.complete = AAZBoolType(
                flags={"read_only": True},
            )
            _element.completed_steps = AAZListType(
                serialized_name="completedSteps",
            )
            _element.content_identifier = AAZObjectType(
                serialized_name="contentIdentifier",
            )
            _element.current_step = AAZStrType(
                serialized_name="currentStep",
                flags={"read_only": True},
            )
            _element.id = AAZStrType()
            _element.object_id = AAZStrType(
                serialized_name="objectId",
            )
            _element.processing_type = AAZIntType(
                serialized_name="processingType",
            )
            _element.remaining_steps = AAZListType(
                serialized_name="remainingSteps",
            )
            _element.steps = AAZListType()

            completed_steps = cls._schema_on_200.Element.completed_steps
            completed_steps.Element = AAZStrType()

            content_identifier = cls._schema_on_200.Element.content_identifier
            content_identifier.canonical_id = AAZStrType(
                serialized_name="canonicalId",
            )
            content_identifier.content_source_profile_name = AAZStrType(
                serialized_name="contentSourceProfileName",
            )
            content_identifier.file_name = AAZStrType(
                serialized_name="fileName",
                flags={"read_only": True},
            )
            content_identifier.multipart_id = AAZListType(
                serialized_name="multipartId",
            )
            content_identifier.unique_id = AAZStrType(
                serialized_name="uniqueId",
                flags={"read_only": True},
            )

            multipart_id = cls._schema_on_200.Element.content_identifier.multipart_id
            multipart_id.Element = AAZStrType()

            remaining_steps = cls._schema_on_200.Element.remaining_steps
            remaining_steps.Element = AAZStrType()

            steps = cls._schema_on_200.Element.steps
            steps.Element = AAZObjectType()

            _element = cls._schema_on_200.Element.steps.Element
            _element.id = AAZStrType()
            _element.parameters = AAZDictType()

            parameters = cls._schema_on_200.Element.steps.Element.parameters
            parameters.Element = AAZStrType()

            return cls._schema_on_200


class _ShowHelper:
    """Helper class for Show"""


__all__ = ["Show"]
